### ISSUE TITLE
Contract failing when depositing tokens  to claim 

### ISSUE THREAD

**Issue by AyiSoli** [CoinGovernanceSystem/cgs-issues#3]
**Describe the bug**
Send tokens to a claim

**To Reproduce**
1. Go to Telephone claim
2. Click on Claim, Deposit 1000 and execute the contract 
3. See error: https://kovan.etherscan.io/tx/0x5912a85dfb770241c17422d1ae65e472ef1ce25f7090aa8e72703c7364832cdc

Error in metamask: Transaction Error. Exception thrown in contract code.

**Expected behavior**
Contract to progress

**Comment by jamesowens91** [comment]
I am having the same error with the same ICO.

**Describe the bug**
I tried depositing some TLF tokens to the smart contract to participate in the claim for the Telephone ICO (here is a screenshot: https://www.dropbox.com/s/4en21t3q6weq8kc/initial-deposit.JPG?dl=0).

However, out of the two transactions that follow only the first one (which goes to the ICO contract address: https://kovan.etherscan.io/tx/0x7a181f3048d307b023e26eb038f8ffde6dce2d4d8ce35417a30f4d1379c625ef) succeeds, while the second one (which I assume moves the tokens to the escrow contract) doesn't: https://kovan.etherscan.io/tx/0x196daa6b5b51d098da6057e4bc3a215a87bc74b4ee25d4171e7f7428da735e1e.

I tried three more times (with progressively higher gas limits, the last one of which is the very high one suggested by Metamask) to no avail:
1a) https://kovan.etherscan.io/tx/0x2f30918ffad3991acbe8d121924844c96c0ed2bbf98c46be4358c06a8c7ac484
1b) https://kovan.etherscan.io/tx/0xdf18454d05f9d0e5532b2612e2a4c02ea7f52e1d227c370d080009a991324d40
2a) https://kovan.etherscan.io/tx/0xa4dabf396740b970c5aca6983d2a00a190a1f5a347cd02d67a810387d75484b6
2b) https://kovan.etherscan.io/tx/0x347a6f91acb82973393c8ecfd33852a72f8e24784646d2e1bc1ed2096cd658df
3a) https://kovan.etherscan.io/tx/0xea50ada44edc1b4a4d17f4ba772e46ba594f209b243da1f0129e2f7ff329725b
3b) https://kovan.etherscan.io/tx/0xfe98c2ac1799dfc300111a4e9047ce5f4dc41c4fec4ab35b20e996a8d2203ed8

**To reproduce**
1) Attempt to deposit TLF tokens via the "Claim" button in the Telephone ICO page (https://testnet.cgs.vote/projects/32);
2) Approve both transactions that follow;
3) Second one will most probably fail.

**Expected Behaviour**
The second transaction should go through instead of failing, especially considering that a gas limit between 150000 and 200000 should be enough for any smart contract to execute.

**Desktop**
OS: Windows 10 Education
Browser (info pasted from "About Brave"):
-----Brave: 0.22.727 
-----V8: 6.6.346.32 
-----rev: 2c94bbad00d70b87328f04574725979960e18f9f 
-----Muon: 6.0.12 
-----OS Release: 10.0.16299 
-----Update Channel: Release 
-----OS Architecture: x64 
-----OS Platform: Microsoft Windows 
-----Node.js: 7.9.0 
-----Brave Sync: v1.4.2 
-----libchromiumcontent: 66.0.3359.170

**Edit**: after this, I successfully deposited ATAT tokens to participate in the claim deposit for the AT-AT ICO, so this issue seems limited to just the Telephone ICO.

**Comment by AdrianClv** [comment]
Thanks @AyiSoli & @jamesowens91 

This problem should be now fixed. It was a problem of synchronization in Parity.
